const menu = [
  {
    id: 1,
    title: "Dave's Combo",
    category: 'lunch',
    price: 11.99,
    img: '/images/dave_burger_combo.png',
    desc: 'This is the famous burger everyone is talking about, get it now with a side of fries and a drink included.',
  },
  {
    id: 2,
    title: 'Breakfast Baconator',
    category: 'breakfast',
    price: 9.99,
    img: '/images/breakfast_combo.png',
    desc: 'This is the famous burger everyone is talking about, get it now with a side of fries and a drink included.',
  },
  {
    id: 3,
    title: 'Double Cheese Burger',
    category: 'lunch',
    price: 8.99,
    img: '/images/burger_only.png',
    desc: 'This is the famous burger everyone is talking about, get it now with a side of fries and a drink included.',
  },
  {
    id: 4,
    title: 'Maple Croissant',
    category: 'breakfast',
    price: 9.99,
    img: '/images/maple_croissant.png',
    desc: 'This is the famous burger everyone is talking about, get it now with a side of fries and a drink included.',
  },
  {
    id: 5,
    title: 'Chicken Sandwich',
    category: 'lunch',
    price: 8.99,
    img: '/images/chicken_only.png',
    desc: 'This is the famous burger everyone is talking about, get it now with a side of fries and a drink included.',
  },
  {
    id: 6,
    title: 'French Toast Sticks',
    category: 'breakfast',
    price: 6.99,
    img: '/images/french_toast.png',
    desc: 'This is the famous burger everyone is talking about, get it now with a side of fries and a drink included.',
  },
  {
    id: 7,
    title: 'Apple Pecan Salad',
    category: 'lunch',
    price: 7.99,
    img: '/images/salad_only.png',
    desc: 'This is the famous burger everyone is talking about, get it now with a side of fries and a drink included.',
  },
  {
    id: 8,
    title: 'Chili with Fries',
    category: 'lunch',
    price: 5.99,
    img: '/images/fries_and_sides.png',
    desc: 'This is the famous burger everyone is talking about, get it now with a side of fries and a drink included.',
  },
  {
    id: 9,
    title: 'Breakfast Biscuit ',
    category: 'breakfast',
    price: 4.99,
    img: '/images/biscuit_combo.png',
    desc: 'This is the famous burger everyone is talking about, get it now with a side of fries and a drink included.',
  },
]

export default menu
